sudo: false

language: node_js

node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"

before_install:
  - touch ~/test.txt
  - echo adddasdasf > ~/test.txt
  - export TEST_VAR=~/test.txt
  - echo TEST $TEST_VAR
  - echo TEST_ENV $TEST_THIS_NOW
  - cat $TEST_VAR

script:
  - npm run-script coveralls