sudo: false

language: node_js

node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"

before_install:
  - touch test.txt
  - export TEST_VAR=$(pwd)/test.txt
  - echo TEST $TEST_VAR

script:
  - npm run-script coveralls